### ISSUE TITLE
MessageBus dependency

### ISSUE THREAD

**Issue by jaymecd** [SimpleBus/Serialization#2]
Is it really required to have `simple-bus/message-bus` as required dependency, as no single class/interface is used from MessageBus, in respect of POPO?

**Comment by matthiasnoback** [comment]
You are right :) Well spotted. I'll change it right-away.

**Comment by matthiasnoback** [comment]
Fixed this for the JMSSerializerBridge as well. So these packages should provide you with some truly decoupled message serialization tools now ;)

**Comment by jaymecd** [comment]
thank you @matthiasnoback
