### ISSUE TITLE
Typo in MessageInEnvelopSerializer

### ISSUE THREAD

**Issue by holtkamp** [SimpleBus/Serialization#4]
See https://github.com/SimpleBus/Serialization/blob/2e81f8789ea6c0df48509b98a07490a0fb480032/src/Envelope/Serializer/MessageInEnvelopSerializer.php#L7

This probably should be ```MessageInEnvelopeSerializer```, also implies a different file name => major change?

**Comment by matthiasnoback** [comment]
Good point, it wouldn't deserve a new major release imo. To fix it one
could use `class_alias()`.

**Comment by holtkamp** [comment]
not a biggie indeed, but good to know..

>To fix it one could use `class_alias()`.

Well, I use it mainly with the ```::class``` constant, like here:
https://github.com/holtkamp/simplebus-asynchronous-bernard-sqs/blob/442173eee5a9c000899428599d711e6a6b18a6ae/src/dic/Config.SimpleBus.CommandBus.Asynchronous.php#L34

Can live with it 😄 , maybe "one day" there will be a new major release that can include this change?

**Comment by cmodijk** [comment]
We can create a second file 'MessageInEnvelopeSerializer' and let the old 'MessageInEnvelopSerializer' extend the correct one and in the old one we can add a deprecation message like Symfony does and remove the old one when we bump the major version. 
* http://symfony.com/doc/current/contributing/code/conventions.html#deprecations

**Comment by cmodijk** [comment]
@holtkamp I created a pull request can you check this for me? https://github.com/SimpleBus/Serialization/issues/4

**Comment by holtkamp** [comment]
@cmodijk seems an elegant approach to deal with this 👍

**Comment by cmodijk** [comment]
I'm closing this issue as we have a pull open pull request.
